name: flutter_calc_game
description: flutter calc game
publish_to: 'none'

version: 1.0.0+1

environment:
#  sdk: '>=3.1.0-11.0.dev <4.0.0'
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^5.2.1
  logging: ^1.1.0
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  firebase_core: ^2.1.1
  firebase_crashlytics: ^3.0.3
  games_services: ^3.0.0
  google_mobile_ads: ^2.0.1
  in_app_purchase: ^3.0.1
  url_launcher: ^6.1.7
  animated_text_kit: ^4.2.2
  dotted_border: ^2.0.0+3
  percent_indicator: ^4.2.2
  sqflite: ^2.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.1
  test: ^1.19.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  image_path_android: "assets/images/default_icon.png"
  image_path_ios: "assets/images/default_icon.png"
  android: true
  ios: true
  image_path: "assets/images/default_icon.png"
  adaptive_icon_background: "#FFEBB5"
  adaptive_icon_foreground: "assets/images/default_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/images/default_icon.png"
    background_color: "#FFEBB5"
    theme_color: "#FFEBB5"
  windows:
    generate: true
    image_path: "assets/images/default_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/default_icon.png"