name: flutter_calc_game

on:
  push:
    branches: pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
#          baseHref: /flutter_calc_game/
#          baseHref: /
          baseHref: /web/
#          webRenderer: canvaskit